GET http://localhost:3333/school
###
GET http://localhost:3333/school/1

###
POST http://localhost:3333/feedback/1
Content-Type: application/json
{
  "name": "Escola Estadual",
  "message":"teste",

}
